3E. Example with questions
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
 prior <- rep( 1 , 1000 )
 likelihood <- dbinom( 6 , size=9 , prob=p_grid )
 posterior <- likelihood * prior
 posterior <- posterior / sum(posterior)
 set.seed(100)
 samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )
 
 #3E1. How much post prob below p=0.2
 sum(samples<0.2)/1e4
 #3E3. How much post prob between p[0.2,0.8]?
 sum(samples>0.2 & samples<0.8)/1e4 #posterior probability between 
 #3E5. 20% post prob lies above which value of p?
 quantile(samples,0.8)
```

3M2. Draw 10,000 samples from above example, estimate 90% HDPI
```{r}
p_grid <- seq( from=0 , to=1 , length.out=1000 )
 prior <- rep( 1 , 1000 )
 likelihood <- dbinom( 8 , size=15 , prob=p_grid )
 posterior <- likelihood * prior
 posterior <- posterior / sum(posterior)
 #set.seed(100) <- has sets of random generated numbers that will be the same across all 
 samples <- sample( p_grid , prob=posterior , size=1e5 , replace=TRUE )

 HPDI(samples,prob=0.9)
 dens(samples,show.HPDI=0.9)
```


3M6. Same Example: Want 99% percentile c(0.005,0.995) to be only p=0.05 wide How many times do i have to toss the globe?
ANS: it depends on my observations? Likelihood is changing based on occurrences and size of samples IDK?
```{r}
#creating sample with random observation and random size

set.seed(100)
n<-2400 #should use function that will automate testing of different n
p_grid <- seq( from=0 , to=1 , length.out=1000 )
 prior <- rep( 1 , 1000 )
 obs<-rbinom( 1 , n , prob=0.7 )
 likelihood <- dbinom( obs , size=n , prob=p_grid )
 posterior <- likelihood * prior
 posterior <- posterior / sum(posterior)
 
 samples <- sample( p_grid , prob=posterior , size=1e4 , replace=TRUE )


p_range<-quantile(samples, c(0.005,0.995)) #middle 99% as Percentile Interval
max(p_range)-min(p_range) # is supposed to be 0.05 or less
```
3H. Use the below data for hard exercises
```{r}
 library(rethinking)
 data(homeworkch3)
 sum(birth1) + sum(birth2)
```
3H3.Use rbinom to simulate 10,000 replicates of 200 births
```{r}
sim_birth <- rbinom(1e4,size=200, prob=samples)


```